### ISSUE TITLE
BigQuery data available?

### ISSUE THREAD

**Issue by rothgar** [kubernetes-incubator/spartakus#23]
Is the BigQuery data available somewhere for others to search through?

I didn't see a link anywhere but would like to query the data for some research.

**Comment by thockin** [comment]
I have not published data because uptake has been low (we haven't really
advertised this much, so it's not surprising).  We have about 3000 unique
nodes that have reported in, and about 15 clusters that seem to be
reporting in on a regular basis.

In short, I ran out of time to keep working on this, and we dropped the
ball.

I am happy to dump the data for you, if you want.

**Comment by rothgar** [comment]
I assumed the set would be pretty small. I'd be interested in looking through it for some idea on where kubernetes can improve.
If there's enough data I may write up a findings post similar to https://medium.com/@rothgar/infrastructure-survey-results-ec6ab950c5b
Not sure how you want to dump the data (or what format it's in) but you can email or share it with me at justinleegarrison@gmail.com
Thanks

**Comment by thockin** [comment]
I've dumped the data to
https://storage.googleapis.com/kubernetes.io/spartakus/data/2017/05-12.json
