### ISSUE TITLE
Consider supporting flags outside of deployment

### ISSUE THREAD

**Issue by justinsb** [kubernetes-incubator/spartakus#4]
So that we can easily upgrade the deployment, maybe we could put the flags outside of the container?

I am thinking of a componentconfig-style typed object, that lives either in a ConfigMap or simply a well known annotation on the kube-system namespace.

In addition, we could then provide additional metadata... for example the installation tool could include a set of tags ("aws kops")

**Comment by viglesiasce** [comment]
I was thinking of this exact kind of thing for having well known flags to label the cluster. For example you could have something like:
- environment: dev, staging, production
- install-mechanism: minikube, kubeadm, gke, etc

This could help in the analysis of the data to partition out various use cases.

**Comment by dasmb** [comment]
@viglesiasce Yeah this is a great value -- otherwise, your data may include lots of small, nondurable clusters mixed in with large, battle-tested clusters.

I suggest adding "prototype" to the list of environments, identifying a cluster that's likely small and temporary. Many minikubes will otherwise skew the data.

And I suggest breaking "install mechanism" into three pieces:
- Target datacenter (named public cloud vs. an unnamed private DC)
- Hosting type (kubeadm, hyperkube, traditional Hard Way, etc)
- Install Manager/Mechanism (gke, kargo, handrolled cluster, kompos8, Stackpoint, Tectonic etc; this gives us a way to shout out the popular installers and identify what techniques are "production proven" vs "fastest to hello world")
